# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/hdl/Boards/MINIZED/minized_LEDs.xdc

# XDC: imports/hdl/Boards/bitstream_compression_enable.xdc

# XDC: imports/hdl/Projects/minized_petalinux/minized_petalinux.xdc

# Block Designs: bd/minized_petalinux/minized_petalinux.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux || ORIG_REF_NAME==minized_petalinux} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_wireless_mgr_0_0/minized_petalinux_wireless_mgr_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_wireless_mgr_0_0 || ORIG_REF_NAME==minized_petalinux_wireless_mgr_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_gpio_0_0 || ORIG_REF_NAME==minized_petalinux_axi_gpio_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_gpio_1_0 || ORIG_REF_NAME==minized_petalinux_axi_gpio_1_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/minized_petalinux_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_iic_0_0 || ORIG_REF_NAME==minized_petalinux_axi_iic_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_axi_uart16550_0_0 || ORIG_REF_NAME==minized_petalinux_axi_uart16550_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_processing_system7_0_0/minized_petalinux_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_processing_system7_0_0 || ORIG_REF_NAME==minized_petalinux_processing_system7_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_ps7_0_axi_periph_0/minized_petalinux_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_ps7_0_axi_periph_0 || ORIG_REF_NAME==minized_petalinux_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_50M_0/minized_petalinux_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_rst_ps7_0_50M_0 || ORIG_REF_NAME==minized_petalinux_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconcat_0_0/minized_petalinux_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconcat_0_0 || ORIG_REF_NAME==minized_petalinux_xlconcat_0_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xlconstant_1_0/minized_petalinux_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xlconstant_1_0 || ORIG_REF_NAME==minized_petalinux_xlconstant_1_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_xbar_0/minized_petalinux_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_xbar_0 || ORIG_REF_NAME==minized_petalinux_xbar_0} -quiet] -quiet

# IP: bd/minized_petalinux/ip/minized_petalinux_auto_pc_0/minized_petalinux_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==minized_petalinux_auto_pc_0 || ORIG_REF_NAME==minized_petalinux_auto_pc_0} -quiet] -quiet

# XDC: bd/minized_petalinux/minized_petalinux_ooc.xdc
