# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z007sclg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.cache/wt [current_project]
set_property parent.project_path /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:minized:part0:1.2 [current_project]
set_property ip_repo_paths /apps_home/home/sroussea/VivadoProjects/hdl/IP [current_project]
set_property ip_output_repo /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/hdl/minized_petalinux_wrapper.vhd
add_files /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/minized_petalinux.bd
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_0_0/minized_petalinux_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_gpio_1_0/minized_petalinux_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/minized_petalinux_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_iic_0_0/minized_petalinux_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_axi_uart16550_0_0/minized_petalinux_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_processing_system7_0_0/minized_petalinux_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_50M_0/minized_petalinux_rst_ps7_0_50M_0_board.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_50M_0/minized_petalinux_rst_ps7_0_50M_0.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_rst_ps7_0_50M_0/minized_petalinux_rst_ps7_0_50M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_xbar_0/minized_petalinux_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/ip/minized_petalinux_auto_pc_0/minized_petalinux_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/sources_1/bd/minized_petalinux/minized_petalinux_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/MINIZED/minized_LEDs.xdc
set_property used_in_implementation false [get_files /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/MINIZED/minized_LEDs.xdc]

read_xdc /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/bitstream_compression_enable.xdc
set_property used_in_implementation false [get_files /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/constrs_1/imports/hdl/Boards/bitstream_compression_enable.xdc]

read_xdc /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/constrs_1/imports/hdl/Projects/minized_petalinux/minized_petalinux.xdc
set_property used_in_implementation false [get_files /apps_home/home/sroussea/VivadoProjects/hdl/Projects/minized_petalinux/MINIZED/minized_petalinux.srcs/constrs_1/imports/hdl/Projects/minized_petalinux/minized_petalinux.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top minized_petalinux_wrapper -part xc7z007sclg225-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef minized_petalinux_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file minized_petalinux_wrapper_utilization_synth.rpt -pb minized_petalinux_wrapper_utilization_synth.pb"
